# Generated by Django 6.0.3 on 2026-04-05 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='name',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='capsula',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='capsula',
            name='link',
        ),
        migrations.RemoveField(
            model_name='capsula',
            name='mensagem',
        ),
        migrations.CreateModel(
            name='ItemImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('imagem', models.ImageField(upload_to='capsulas/')),
                ('capsula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core.capsula')),
            ],
        ),
        migrations.CreateModel(
            name='ItemLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField()),
                ('capsula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.capsula')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('texto', models.TextField()),
                ('capsula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textos', to='core.capsula')),
            ],
        ),
    ]
